var ticker = new Array('<a href="http://beszeljukmac.com/index.php/weblog/comments/beszelgetes_a_vlc_2.0_fejlesztoivel/" target="_new">Beszélgetés a VLC 2.0 fejlesztőivel</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/iphone_5_csak_sszel/" target="_new">iPhone 5 csak ősszel</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/elzetesben_az_apple_hirekkel_keresked_tzsdei_elemz_o/" target="_new">Előzetesben az Apple hírekkel kereskedő tőzsdei elemző</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/kepernyzar_feloldas_kie_a_gesztus_szabadalma/" target="_new">Képernyőzár feloldás: kié a gesztus szabadalma?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/antenna-gate_ujabb_birosagi_hatarozat/" target="_new">Antenna-gate: újabb bírósági határozat</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/tovabbi_ujdonsagok_az_os_x_10.8-ban/" target="_new">További újdonságok az OS X 10.8-ban</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/ipad_3_pletykak_8_megapixeles_kamera_es_a5s_processzor/" target="_new">iPad 3 pletykák: 8 megapixeles kamera és A5S processzor?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/ios_fejlesztes_itt_mindent_megtudsz_a_kezdetekrl1/" target="_new">iOS fejlesztés: itt mindent megtudhatsz a kezdetekről</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/vissszatartja_az_intel_az_ivy_bridge_processzorok_megjeleneset/" target="_new">Vissszatartja az Intel az Ivy Bridge processzorok megjelenését?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/ios_grafika_mi_ez_az_igenytelenseg/" target="_new">iOS grafika: mi ez az igénytelenség?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/os_x_10.8_epul_a_kerites/" target="_new">OS X 10.8: épül a kerítés</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/os_x_10.8_a_felho_es_a_vallalati_piac/" target="_new">OS X 10.8: a felhő és a vállalati piac</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/os_x_mountain_lion_teljes_game_center_tamogatas/" target="_new">OS X Mountain Lion: teljes Game Center támogatás</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/uj_szelek_az_apple_es_a_sajto_viszonyaban/" target="_new">Új szelek az Apple és a sajtó viszonyában?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/akiknek_kellemetlen_lesz_az_os_x_10.8_megjelenese/" target="_new">Akiknek kellemetlen lesz az OS X 10.8 megjelenése</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/airplay_mirroring_az_os_x_10.8-ban/" target="_new">AirPlay Mirroring az OS X 10.8-ban</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/laptop_tablagep_tim_cook_szerint_barmi_lehetseges_a_joevben/" target="_new">Laptop? Táblagép? Tim Cook szerint bármi lehetséges a jövőben</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/messages/" target="_new">Messages</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/macroscalar_processzor_az_apple_koevetkez_nagy_dobasa/" target="_new">Macroscalar processzor: az Apple következő nagy dobása?</a>',
'<a href="http://beszeljukmac.com/index.php/weblog/comments/fejlesztknel_az_os_x_lion_mountain_lion_els_valtozata/" target="_new">Fejlesztőknél az OS X Mountain Lion első változata!</a>',
'');